Phase01 search completed.
Star-Academy/Fall1402-TwoWeek-InternShip-Backend pull request #1
Opened 2023-11-19 14:34 UTC by MohammadHDehghani

2023-11-22 14:29 UTC, RAAvenger requested changes

2023-11-22 14:29 UTC, RAAvenger commented on Main.java
> +        String user_input = myScanner.nextLine();
از نام گذاری استاندارد جاوا استفاده بشه بهتره

2023-11-22 14:29 UTC, RAAvenger commented on Main.java
> +        ArrayList<Entry_Structure> words_list = new ArrayList<Entry_Structure>();   // An array list for storing words and file name
بهتر نیست بزنید var؟

2023-11-22 14:29 UTC, RAAvenger commented on Main.java
> +        ArrayList<Entry_Structure> words_list = new ArrayList<Entry_Structure>();   // An array list for storing words and file name
متغییر بهتره جایی تعریف بشه که قراره استفاده بشه

2023-11-22 14:29 UTC, RAAvenger commented on Main.java
> +                word = word.replace('+', ' ');
میتونن یکی بشن

2023-11-22 14:29 UTC, RAAvenger commented on Main.java
> +        ArrayList<String> file_names_in_folder = FileReader.getFileNames("./EnglishData/");
میتونه const تعریف بشه

2023-11-22 14:29 UTC, RAAvenger commented on Entry_Structure.java
> +    public void setWord(String word) {
با توجه به منطق کلاس این لازمه؟

2023-11-22 14:29 UTC, RAAvenger commented on Entry_Structure.java
> +    }
با توجه به منطق کلاس این لازمه؟

2023-11-22 14:29 UTC, RAAvenger commented on Entry_Structure.java
> +    }
میشه از getter استفاده کرد

2023-11-22 14:29 UTC, RAAvenger commented on Entry_Structure.java
> +    }
میشه از getter استفاده کرد

2023-11-22 14:29 UTC, RAAvenger commented on Main.java
بهتره منطق ساختن inverted index با توجه به صحبتمون اصلاح بشه

2023-11-23 06:20 UTC, MohammadHDehghani commented on Main.java
> +        String user_input = myScanner.nextLine();
نام گذاری ها اصلاح شد.

2023-11-23 06:21 UTC, MohammadHDehghani commented on Main.java
> +        ArrayList<Entry_Structure> words_list = new ArrayList<Entry_Structure>();   // An array list for storing words and file name
محل تعریف متغیر به جایی که از اون استفاده شده منتقل شد.

2023-11-23 06:21 UTC, MohammadHDehghani commented on Main.java
> +                word = word.replace('+', ' ');
تغییرات مدنظر اعمال شد.

2023-11-23 06:21 UTC, MohammadHDehghani commented on Main.java
> +        ArrayList<String> file_names_in_folder = FileReader.getFileNames("./EnglishData/");
آدرس فایل به صورت کانست تعریف شد و مقدار آن هم از کاربر گرفته می‌شود.

2023-11-23 06:21 UTC, MohammadHDehghani commented on Entry_Structure.java
> +    public void setWord(String word) {
حذف شد.

2023-11-23 06:21 UTC, MohammadHDehghani commented on Entry_Structure.java
> +    }
حذف شد.

2023-11-23 06:22 UTC, MohammadHDehghani commented on Main.java
منطق برنامه اصلاح شد. درحال حاضر inverted index در حین خوانده شدن فایل ها ساخته میشه و دیگه یک حلقه اضافه نداریم.

2023-11-23 06:25 UTC, MohammadHDehghani commented on Main.java
> +        ArrayList<Entry_Structure> words_list = new ArrayList<Entry_Structure>();   // An array list for storing words and file name
با توجه به تغییراتی که در منطق برنامه اعمال شد این خط از کد حذف شد.

2023-11-23 07:12 UTC, MohammadHDehghani commented on Entry_Structure.java
> +    }
با استفاده از lombok از تابع getter استفاده کردیم.

2023-11-23 07:12 UTC, MohammadHDehghani commented on Entry_Structure.java
> +    }
با استفاده از lombok از تابع getter استفاده کردیم.

2023-11-23 07:14 UTC, MohammadHDehghani commented
به خاطر احتمال ایجاد کانفلیکت هنگام مرج، تصمیم بر این شد که فایل‌های مربوط به پروژه های در دایرکتوری‌های مجزا از هم قرار گیرد و در برنچ‌های جدید پوش شود.
تغییرات گفته شده در کد اعمال شد و کدهای جدید روی برنچ phase01-search-corrected پوش شدند.

2023-11-25 18:13 UTC, closed without merging